### ISSUE TITLE
Followers and following list is now empty.

### ISSUE THREAD

**Issue by cybercatgurrl** [cybercatgurrl/Capella#22]
@silasary pretty sure merging your commit did that. i'm workin on something else atm so i don't know where to check just yet.

**Comment by silasary** [comment]
Oh, I know where that would have happened.  That should be an easy fix.

Completely empty, or just no text?

**Comment by cybercatgurrl** [comment]
Completely empty. It should be listing user profiles in a giant list when clicking on followers or following.
